spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
    password: 123456
    username: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update






xl-apiPakeage: com.xl.missyou.api


